services:
    db:
        image: mysql:5.7
        user: "1000:1000"
        volumes:
            - ${MYSQL_DATA_PATH}:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3307:3306
        networks:
            - upfront_network

    app_upfront_backend:
        build: docker_web_8_2/
        volumes:
            - ${APP_UPFRONT_PATH}backend:/app/upfront_backend:cached
        links:
            - db
        working_dir: /app/upfront_backend
        ports:
            - 8000:8000
        networks:
            - upfront_network
        depends_on:
            - db
        tty: true
        command: [ "/bin/bash", "-c", "/usr/local/bin/wait-for-it.sh db:3306 --timeout=600 --strict -- /bin/bash start_backend.sh" ]


    app_upfront_frontend:
        build: docker_web_8_2/
        volumes:
            - ${APP_UPFRONT_PATH}frontend:/app/upfront_frontend:cached
        links:
            - db
        working_dir: /app/upfront_frontend
        ports:
            - 8080:8080
        networks:
            - upfront_network
        depends_on:
            - db
            - app_upfront_backend
        tty: true
        command: [ "/bin/bash", "-c", "/usr/local/bin/wait-for-it.sh db:3306 --timeout=600 --strict -- /bin/bash start_frontend.sh" ]

networks:
    upfront_network:
        driver: bridge
